version: "2.2"
services:
  comic_reader_app:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: comic_reader_app
    env_file: .env.production
    ports:
      - "8080:80"
    volumes:
      - ".:/app"
