version: "3.3"
services:
  redis:
    image: redis
    container_name: "redis"
  api:
    build: .
    container_name: "comic_reader_api_dev"
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
    volumes:
      - .:/app
  worker:
    build: .
    container_name: "celery_worker"
    command: celery -A celery_worker.celery worker --pool=solo --loglevel=info 
    depends_on:
      - "redis"
    volumes:
      - .:/app
