version: "3.9"
services:
  redis:
    image: redis
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "redis"
    volumes:
      - .:/app
  worker:
    build: .
    command: celery -A celery_worker.celery worker --pool=solo --loglevel=info 
    depends_on:
      - "redis"
    volumes:
      - .:/app
